### ISSUE TITLE
Bug in Y2Axis Scaling in Scale.cs

### ISSUE THREAD

**Issue by nerndt** [saleyn/ZedGraph#1]
Fix is:

      // If this is a Y axis, and the main Y axis is valid, use it for defaults
      if (_ownerAxis is IYAxis)
      {
        Scale scale;
        if (pane.YAxis.Scale.Valid && _ownerAxis is YAxis) // NGE12162020 Added  && _ownerAxis is YAxis
            scale = pane.YAxis.Scale;
        else if (pane.Y2Axis.Scale.Valid && _ownerAxis is Y2Axis) // NGE12162020 Added  && _ownerAxis is Y2Axis
            scale = pane.Y2Axis.Scale;
        else
          return;

        if (ReferenceEquals(this, scale))
          return;

        _rangeMin = scale._rangeMin;
        _rangeMax = scale._rangeMax;
      }

**Comment by saleyn** [comment]
Could you submit this as a pull request?

**Comment by nerndt** [comment]
Hi Serge,
I must apologize but I do not know how to submit it as a pull request.  I cloned the repository, made the 2 lines of code cahnge in Scale.cs, but do not know what to do next.
Take care, Nick Nick Erndt nerndt@yahoo.com hm 650 493-7607 mobile 650 906-5970 

    On Friday, December 18, 2020, 10:27:58 AM PST, Serge Aleynikov <notifications@github.com> wrote:  
 
 


Could you submit this as a pull request?

**Comment by saleyn** [comment]
It is pretty easy, as outlined here:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by nerndt** [comment]
Did you receive the pull request?

**Comment by nerndt** [comment]
Added pull request

**Comment by saleyn** [comment]
Thank you! Merged.
